#! /bin/sh



bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4' state=floating
bspc rule -a Acroread state=tiled

feh --bg-center ~/pics/wallhaven-12880.jpg &

sxhkd &

export TERM=rxvt &

perWindowLayoutD &
~/scripts/lemon.sh | lemonbar -p -g 1576x26+10+4 -u 2 -f "Cantarell:size=12" -f "Font Awesome:size=14"


#~/scripts/.reader.sh | lemonbar -p -f "Font Awesome" -f "Cantarell" -g 1000x20+12+4 -u 2 &
#~/scripts/.lemon.py &
