#! /bin/sh



bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4' state=floating
bspc rule -a Acroread state=tiled

feh --bg-center ~/pics/wallhaven-87808.jpg &

sxhkd &

perWindowLayoutD &
~/scripts/lemon.sh | lemonbar -p -g 1576x20+12+4 -u 2 -f "Cantarell:size=10" -f "Font Awesome:size=12"
